apiVersion: v1
kind: Secret
metadata:
  name: dvwa-mysql-secret
  namespace: dvwa
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: mypass123
  MYSQL_DATABASE: dvwa
  MYSQL_USER: dvwa_user
  MYSQL_PASSWORD: mypass123
