apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-web
  namespace: dvwa
  labels:
    app: dvwa
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
      tier: frontend
  template:
    metadata:
      labels:
        app: dvwa
        tier: frontend
    spec:
      containers:
      - name: dvwa
        image: vulfocus/dvwa:latest # A commonly used DVWA Docker image
        env:
        - name: DB_HOST
          value: dvwa-mysql # Matches the Service name for the database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dvwa-mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvwa-mysql-secret
              key: MYSQL_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dvwa-mysql-secret
              key: MYSQL_DATABASE
        ports:
        - containerPort: 80 # DVWA runs on port 80 inside the container
          name: http
