apiVersion: v1
kind: Service
metadata:
  name: dvwa-web
  namespace: dvwa
  labels:
    app: dvwa
    tier: frontend
spec:
  selector:
    app: dvwa
    tier: frontend
  ports:
  - protocol: TCP
    port: 80 # The service's port (can be anything, but 80 is logical for HTTP)
    targetPort: 80 # The container's port
    nodePort: 30081 # A port on your machine accessible from outside (must be 30000-32767)
  type: NodePort # Exposes the service on a port on your Minikube node
